[package]
name = "encode_all"
version = "0.1.0"
authors = ["poccariswet <poccariswet2727@gmail.com>"]
edition = "2021"

[dependencies]
apng = { path = "../../" }
png = "0.17.13"
image = { version = "0.25.0", default-features = false, features = ["png"] }
